// Game Database - Sample games data
const gamesData = [
    {
        id: 1,
        title: "Cyber Adventure 2077",
        category: "rpg",
        price: 49.99,
        oldPrice: 69.99,
        rating: 4.8,
        reviews: 12450,
        badge: "hot",
        emoji: "🎮",
        color: "linear-gradient(135deg, #ff6b6b, #ee5a6f)",
        description: "Dive into a futuristic open-world RPG where you shape your own destiny. Explore a vast cyberpunk metropolis, make choices that matter, and uncover hidden secrets.",
        features: ["Open World", "Story Rich", "Character Customization", "Multiplayer", "4K Graphics", "Ray Tracing"],
        releaseDate: "2025-12-15",
        developer: "Neon Studios"
    },
    {
        id: 2,
        title: "Space Wars: Galaxy",
        category: "action",
        price: 39.99,
        oldPrice: 59.99,
        rating: 4.6,
        reviews: 8930,
        badge: "sale",
        emoji: "🚀",
        color: "linear-gradient(135deg, #4ecdc4, #44a08d)",
        description: "Engage in epic space battles across the galaxy. Command your fleet, explore alien worlds, and build your intergalactic empire in this action-packed adventure.",
        features: ["Space Combat", "Fleet Management", "Online Multiplayer", "VR Support", "Co-op Mode"],
        releaseDate: "2026-01-20",
        developer: "StarForge Games"
    },
    {
        id: 3,
        title: "Dragon Quest: Legends",
        category: "rpg",
        price: 59.99,
        oldPrice: null,
        rating: 4.9,
        reviews: 15670,
        badge: "new",
        emoji: "⚔️",
        color: "linear-gradient(135deg, #a8edea, #fed6e3)",
        description: "Embark on an epic quest to defeat ancient dragons. Master powerful spells, forge legendary weapons, and become the hero the kingdom needs.",
        features: ["Epic Story", "Magic System", "Boss Battles", "Crafting", "Character Classes"],
        releaseDate: "2026-02-10",
        developer: "Mythic Games"
    },
    {
        id: 4,
        title: "FIFA Football 2026",
        category: "sports",
        price: 69.99,
        oldPrice: 89.99,
        rating: 4.5,
        reviews: 23450,
        badge: "hot",
        emoji: "⚽",
        color: "linear-gradient(135deg, #f093fb, #f5576c)",
        description: "Experience the beautiful game like never before. Realistic graphics, authentic teams, and the most immersive football experience ever created.",
        features: ["Career Mode", "Online Tournaments", "Real Players", "Stadium Atmosphere", "Pro Clubs"],
        releaseDate: "2025-09-25",
        developer: "EA Sports"
    },
    {
        id: 5,
        title: "Need for Speed: Velocity",
        category: "racing",
        price: 44.99,
        oldPrice: 59.99,
        rating: 4.4,
        reviews: 9820,
        badge: "sale",
        emoji: "🏎️",
        color: "linear-gradient(135deg, #fa709a, #fee140)",
        description: "Push your supercar to the limit in high-stakes street races. Customize your ride, master the tracks, and become the ultimate street legend.",
        features: ["Car Customization", "Open World", "Police Chases", "Multiplayer", "Real Cars"],
        releaseDate: "2025-11-12",
        developer: "Velocity Games"
    },
    {
        id: 6,
        title: "Zombie Survival: Last Stand",
        category: "horror",
        price: 29.99,
        oldPrice: 39.99,
        rating: 4.3,
        reviews: 7230,
        badge: "sale",
        emoji: "🧟",
        color: "linear-gradient(135deg, #2c3e50, #4a6741)",
        description: "Survive the zombie apocalypse in this intense survival horror. Scavenge for resources, build shelters, and fight hordes of the undead.",
        features: ["Survival Mechanics", "Base Building", "Co-op Play", "Crafting", "Permadeath Mode"],
        releaseDate: "2025-10-08",
        developer: "Dead Pixel Studios"
    },
    {
        id: 7,
        title: "Empire Builder: Strategy",
        category: "strategy",
        price: 34.99,
        oldPrice: null,
        rating: 4.7,
        reviews: 5640,
        badge: null,
        emoji: "🏰",
        color: "linear-gradient(135deg, #fbc2eb, #a6c1ee)",
        description: "Build your empire from scratch in this deep strategy game. Manage resources, train armies, and conquer your enemies through diplomacy or war.",
        features: ["City Building", "Diplomacy", "Real-time Battles", "Tech Tree", "Multiplayer"],
        releaseDate: "2026-01-05",
        developer: "Strategy Kings"
    },
    {
        id: 8,
        title: "Mystic Forest Adventure",
        category: "adventure",
        price: 24.99,
        oldPrice: 34.99,
        rating: 4.6,
        reviews: 4520,
        badge: "sale",
        emoji: "🌲",
        color: "linear-gradient(135deg, #84fab0, #8fd3f4)",
        description: "Explore a magical forest filled with mysteries. Solve puzzles, befriend magical creatures, and uncover the secrets of the ancient woods.",
        features: ["Puzzle Solving", "Exploration", "Magic System", "Beautiful Art", "Family Friendly"],
        releaseDate: "2025-08-18",
        developer: "Whisper Games"
    },
    {
        id: 9,
        title: "Puzzle Master 3D",
        category: "puzzle",
        price: 19.99,
        oldPrice: 29.99,
        rating: 4.5,
        reviews: 3210,
        badge: null,
        emoji: "🧩",
        color: "linear-gradient(135deg, #a1c4fd, #c2e9fb)",
        description: "Challenge your mind with hundreds of mind-bending 3D puzzles. From simple shapes to complex mechanisms, every level is a new adventure.",
        features: ["500+ Puzzles", "Daily Challenges", "Multiplayer", "Relaxing", "No Ads"],
        releaseDate: "2025-07-22",
        developer: "MindPlex"
    },
    {
        id: 10,
        title: "Assassin's Creed: Shadows",
        category: "action",
        price: 54.99,
        oldPrice: 69.99,
        rating: 4.7,
        reviews: 18760,
        badge: "hot",
        emoji: "🗡️",
        color: "linear-gradient(135deg, #232526, #414345)",
        description: "Become a legendary assassin in feudal Japan. Master the way of the ninja, uncover conspiracies, and write your own legend in this open-world epic.",
        features: ["Stealth Combat", "Open World", "Parkour", "Historical Setting", "Multiple Endings"],
        releaseDate: "2025-11-30",
        developer: "Ubisoft Montreal"
    },
    {
        id: 11,
        title: "Racing Rivals: Drift King",
        category: "racing",
        price: 39.99,
        oldPrice: null,
        rating: 4.4,
        reviews: 6890,
        badge: "new",
        emoji: "🏁",
        color: "linear-gradient(135deg, #f6d365, #fda085)",
        description: "Master the art of drifting in this adrenaline-pumping racing game. Compete against the best drivers worldwide and become the drift king.",
        features: ["Drift Physics", "Car Tuning", "Online Tournaments", "Real Tracks", "Photo Mode"],
        releaseDate: "2026-02-28",
        developer: "Drift Studios"
    },
    {
        id: 12,
        title: "Horror Mansion: The Awakening",
        category: "horror",
        price: 22.99,
        oldPrice: 32.99,
        rating: 4.2,
        reviews: 5430,
        badge: "sale",
        emoji: "👻",
        color: "linear-gradient(135deg, #000000, #434343)",
        description: "Explore a haunted mansion and uncover its dark secrets. Face your fears in this psychological horror that will keep you on the edge of your seat.",
        features: ["Psychological Horror", "Puzzle Solving", "Atmospheric", "Multiple Endings", "VR Compatible"],
        releaseDate: "2025-09-15",
        developer: "Dark Realm Games"
    },
    {
        id: 13,
        title: "Tactical Ops: Modern War",
        category: "strategy",
        price: 44.99,
        oldPrice: 59.99,
        rating: 4.6,
        reviews: 9120,
        badge: null,
        emoji: "🎯",
        color: "linear-gradient(135deg, #283c86, #45a247)",
        description: "Command elite soldiers in modern warfare scenarios. Plan your strategy, execute tactical missions, and lead your team to victory.",
        features: ["Tactical Combat", "Squad Management", "Realistic Weapons", "Multiplayer", "Campaign Mode"],
        releaseDate: "2025-10-20",
        developer: "War Games Inc"
    },
    {
        id: 14,
        title: "Pixel Dungeon Quest",
        category: "rpg",
        price: 14.99,
        oldPrice: 19.99,
        rating: 4.7,
        reviews: 8760,
        badge: null,
        emoji: "🗡️",
        color: "linear-gradient(135deg, #ff9a9e, #fad0c4)",
        description: "A retro-styled dungeon crawler with modern mechanics. Explore procedurally generated dungeons, collect loot, and defeat epic bosses.",
        features: ["Procedural Dungeons", "Loot System", "Pixel Art", "Roguelike", "Class System"],
        releaseDate: "2025-06-12",
        developer: "Retro Games"
    },
    {
        id: 15,
        title: "Sky Sports Champions",
        category: "sports",
        price: 49.99,
        oldPrice: null,
        rating: 4.3,
        reviews: 4320,
        badge: "new",
        emoji: "🏀",
        color: "linear-gradient(135deg, #ff7e5f, #feb47b)",
        description: "Experience multiple sports in one ultimate package. Basketball, football, tennis, and more - all in stunning realism.",
        features: ["Multiple Sports", "Career Mode", "Online Play", "Tournaments", "Real Teams"],
        releaseDate: "2026-03-15",
        developer: "Sports Pro"
    },
    {
        id: 16,
        title: "Mystery Island Escape",
        category: "adventure",
        price: 27.99,
        oldPrice: 39.99,
        rating: 4.5,
        reviews: 3210,
        badge: "sale",
        emoji: "🏝️",
        color: "linear-gradient(135deg, #43cea2, #185a9d)",
        description: "Survive on a mysterious island filled with ancient ruins. Solve puzzles, craft tools, and find a way to escape this beautiful yet dangerous place.",
        features: ["Survival", "Crafting", "Puzzles", "Beautiful Scenery", "Story Driven"],
        releaseDate: "2025-08-30",
        developer: "Island Games"
    }
];

// Categories data
const categories = [
    { name: "Action", icon: "💥", count: 120 },
    { name: "RPG", icon: "⚔️", count: 85 },
    { name: "Sports", icon: "⚽", count: 60 },
    { name: "Racing", icon: "🏎️", count: 45 },
    { name: "Strategy", icon: "🧠", count: 70 },
    { name: "Horror", icon: "👻", count: 35 },
    { name: "Adventure", icon: "🗺️", count: 95 },
    { name: "Puzzle", icon: "🧩", count: 50 }
];
